[[command]]
  name = "zone"
  description = """
  This is a meaty description of the zone api."""
  subcommands = [
    "list-zones",
    "delete-zone",
    "create-zone",
    "edit-zone-paused",
    "edit-zone-vanity-ns",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with zones"

[[command]]
  name = "dns"
  description = """
  This is a meaty description of the dns api."""
  subcommands = [
    "list-dns-records",
    "edit-dns-record",
    "show-dns-record",
    "create-dns-record",
    "delete-dns-record",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with dns records"

[[command]]
  name = "ssl"
  description = """
  This is a meaty description of the ssl api."""
  subcommands = [
    "list-custom-certs",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with ssl configuration"


[[command]]
  name = "pagerules"
  description = """
  This is a meaty description of the pagerules api."""
  subcommands = [
    "list-page-rules",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with pagerules api"

[[command]]
  name = "firewall"
  description = """
  This is a meaty description of the firewall apis."""
  subcommands = [
    "list-user-agent-rules",
    "list-zone-lockdowns",
    "list-waf-packages",
    "list-waf-rules",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with firewall"

[[command]]
  name = "organization"
  description = """
  This is a meaty description of the organizaiton api."""
  subcommands = [
    "list-organizations",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with organizations api"

[[command]]
  name = "ratelimit"
  description = """
  This is a meaty description of the ratelimit api."""
  subcommands = [
    "list-ratelimits",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with ratelimit api"

[[command]]
  name = "loadbalancer"
  description = """
  This is a meaty description of the loadbalancer api."""
  subcommands = [
    "list-loadbalancers",
    "list-loadbalancer-monitors",
    "list-loadbalancer-pools",
  ]
  toplevel = true
  shortdescription = "Commands for interacting with loadbalancer api"

[[command]]
  name = "list-zones"
  description = """
  This is a meaty description of the list-zones"""
  shortdescription = "Command for listing zones"
  v4apiname = "ListZones"
  [[command.option]]
  name = "zone-name-filter"
  type = "string"
  description = "string for filtering by name"
  required = false

[[command]]
  name = "list-dns-records"
  description = """
  List DNS Records associated with a given zone-id"""
  shortdescription = "Command for listing dns-records"
  v4apiname = "DNSRecords"

  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "zone id used for filtering"
  required = true

  [[command.option]]
  name = "type"
  type = "string"
  description = "DNS Record type used for filter"
  required = false

  [[command.option]]
  name = "name"
  type = "string"
  description = "DNS Record name used for filter"
  required = false

  [[command.option]]
  name = "content"
  type = "string"
  description = "DNS Record content used for filter"
  required = false

[[command]]
  name = "create-dns-record"
  description = """Create DNS record associated with a given zone."""
  shortdescription = "Command DNS Record"
  v4apiname = "CreateDNSRecord"

  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* zone id associated with the new dns record"
  required = true

  [[command.option]]
  name = "type"
  type = "string"
  description = "*Required:* valid values: A, AAAA, CNAME, TXT, SRV, LOC, MX, NS, SPF, CERT, DNSKEY, DS, NAPTR, SMIMEA, SSHFP, TLSA, URI read only"
  required = true

  [[command.option]]
  name = "name"
  type = "string"
  description = "*Required:* DNS Record name (example: example.com), max length: 255"
  required = true

  [[command.option]]
  name = "content"
  type = "string"
  description = "*Required:* DNS Record content used for filter"
  required = true

  [[command.option]]
  name = "ttl"
  type = "int"
  description = "Time to live for DNS record. Value of 1 is 'automatic', min value:120 max value:2147483647"
  required = false

  [[command.option]]
  name = "not-proxied"
  type = "bool"
  description = "Whether the record is receiving the performance and security benefits of Cloudflare"
  required = false

  [[command.option]]
  name = "priority"
  type = "int"
  description = "Used with some records like MX and SRV to determine priority. If you do not supply a priority for an MX record, a default value of 0 will be set. min value:0 max value:65535."
  required = false

[[command]]
  name = "delete-dns-record"
  description = """Delete DNS record associated with a given zone."""
  shortdescription = "Delete DNS Record"
  v4apiname = "DeleteDNSRecord"

  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* zone id associated with the record you wish to delete"
  required = true

  [[command.option]]
  name = "recordID"
  type = "string"
  description = "*Required:* record id associated with the dns record you wish to delete"
  required = true

[[command]]
  name = "delete-zone"
  description = """Delete a zone associated with your account."""
  shortdescription = "Delete zone"
  v4apiname = "DeleteZone"

  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* zone id that will be deleted"
  required = true

[[command]]
  name = "create-zone"
  description = """Create a zone associated with your account."""
  shortdescription = "Create zone"
  v4apiname = "CreateZone"

  [[command.option]]
  name = "name"
  type = "string"
  description = "*Required:* the zone name that will be added to your account"
  required = true

  [[command.option]]
  name = "organizationID"
  type = "string"
  description = "The organizationID associated with the zone"
  required = false

[[command]]
  name = "show-dns-record"
  description = """Show a single DNS record associated with a zone ID and record ID."""
  shortdescription = "Show DNS Record"
  v4apiname = "DNSRecord"

  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the DNS Record"
  required = true

  [[command.option]]
  name = "recordID"
  type = "string"
  description = "*Reqiured:* The recordID associated with the DNS Record"
  required = true

[[command]]
  name = "list-ratelimits"
  description = """Returns all Rate Limits for a zone"""
  shortdescription = "Show Ratelimits"
  v4apiname = "ListAllRateLimits"

  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the Ratelimits"
  required = true

[[command]]
  name = "list-loadbalancers"
  description = """Returns all LoadBalancers for a zone"""
  shortdescription = "Show LoadBalancers"
  v4apiname = "ListLoadBalancers"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the Ratelimits"
  required = true

[[command]]
  name = "list-organizations"
  description = """Returns all Organizations associated with your account"""
  shortdescription = "Show Organizations"
  v4apiname = "ListOrganizations"

[[command]]
  name = "list-page-rules"
  description = """Returns all page rules associated with a given zone ID"""
  shortdescription = "Show Page Rules"
  v4apiname = "ListPageRules"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the pagerules"
  required = true

[[command]]
  name = "list-custom-certs"
  description = """Returns all custom certs for a given zone ID"""
  shortdescription = "Show Custom Certs"
  v4apiname = "ListCustomCerts"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the custom certs"
  required = true

[[command]]
  name = "list-user-agent-rules"
  description = """Returns all User-Agent rules for a specific zone ID"""
  shortdescription = "List User-Agent rules"
  v4apiname = "ListUserAgentRules"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the user-agent rule."
  required = true

  [[command.option]]
  name = "page"
  type = "int"
  description = "Pagination for user-agent rules"

[[command]]
  name = "list-waf-packages"
  description = """Return the WAF Packages associated with a given zone."""
  shortdescription = "List WAF Packages"
  v4apiname = "ListWAFPackages"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the WAF packages."
  required = true

[[command]]
  name = "list-waf-rules"
  description = """Return the WAF Rules associated with a given zone."""
  shortdescription = "List WAF Rules"
  v4apiname = "ListWAFRules"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the WAF configuration."
  required = true
  [[command.option]]
  name = "packageID"
  type = "string"
  description = "*Required:* The package ID associated with the displayed WAF rules."
  required = true

[[command]]
  name = "list-zone-lockdowns"
  description = """Return the lockdowns associated with a given lockdown."""
  shortdescription = "List Zone Lockdowns"
  v4apiname = "ListZoneLockdowns"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the WAF configuration."
  required = true
  [[command.option]]
  name = "page"
  type = "int"
  description = "Pagination for zone lockdowns."

[[command]]
  name = "edit-zone-paused"
  description = """Edit a given zone's properties."""
  shortdescription = "Edit a given zone"
  v4apiname = "EditZonePaused"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the zone being updated"
  required = true
  [[command.option]]
  name = "paused"
  type = "bool"
  description = "*Required:* Set to pause the zone while editing the zone"

[[command]]
  name = "edit-zone-vanity-ns"
  description = """Edit a given zone's properties."""
  shortdescription = "Edit a given zone"
  v4apiname = "EditZoneVanityNS"
  [[command.option]]
  name = "zoneID"
  type = "string"
  description = "*Required:* The zone ID associated with the zone being updated"
  required = true
  [[command.option]]
  name = "vanityNS"
  type = "string"
  required = true
  description = "*Required:* Comma delimited list of vanity nameservers"

[[command]]
  name = "edit-dns-record"
  description = """Edit an individual dns record's proxied status."""
  shortdescription = "Edit proxy status for dns record"
  v4apiname = "EditDNSRecord"
  [[command.option]]
  name = "proxied"
  type = "bool"
  description = "Set this flag is you wish to proxy through Cloudflare, otherwise do not set"
  [[command.option]]
  name = "zoneID"
  type = "string"
  required = true
  description = "*Required:* The zone ID associated with the dns record"
  [[command.option]]
  name = "recordID"
  type = "string"
  required = true
  description = "*Required:* The record ID that indicates the dns record"
  [[command.option]]
  name = "type"
  type = "string"
  description = "*Required:* valid values: A, AAAA, CNAME, TXT, SRV, LOC, MX, NS, SPF, CERT, DNSKEY, DS, NAPTR, SMIMEA, SSHFP, TLSA, URI read only"
  required = true
  [[command.option]]
  name = "name"
  type = "string"
  description = "*Required:* DNS Record name (example: example.com), max length: 255"
  required = true
  [[command.option]]
  name = "content"
  type = "string"
  description = "*Required:* DNS Record content used for filter"
  required = true
  [[command.option]]
  name = "ttl"
  type = "int"
  description = "Time to live for DNS record. Value of 1 is 'automatic', min value:120 max value:2147483647"
  required = false

[[command]]
  name = "list-loadbalancer-monitors"
  description = """Returns all LoadBalancer Monitors. Not specific to a zone"""
  shortdescription = "Show LoadBalancer Monitors"
  v4apiname = "ListLoadBalancerMonitors"
[[command]]
  name = "list-loadbalancer-pools"
  description = """Returns all LoadBalancer Pools. Not specific to a zone"""
  shortdescription = "Show LoadBalancer Pools"
  v4apiname = "ListLoadBalancerPools"
